AWSTemplateFormatVersion: 2010-09-09
Metadata:
  Generator: former2
Description: Visitor Prioritization Function
Parameters:
  BucketName:
    Description: Name of the S3 bucket
    Type: String
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaEdgeRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref BucketName
        S3Key: "lambda.zip"
      Description: Visitor prioritization function
      FunctionName: VisitorPrioritization
      Handler: "prioritize.handler"
      MemorySize: 128
      Role: !GetAtt ExecutionRole.Arn
      Runtime: "nodejs10.x"
      Timeout: 3
      Tags:
        -
          Key: "Demo"
          Value: "true"
        -
          Key: "Project"
          Value: "Visitor prioritization"
  ExecutionPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: LambdaEdgePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "iam:CreateServiceLinkedRole"
            Resource: "arn:aws:iam::*:role/*"
          - Effect: Allow
            Action:
              - "lambda:GetFunction"
              - "lambda:EnableReplication"
            Resource: !GetAtt Function.Arn
          - Effect: Allow
            Action:
              - "cloudfront:UpdateDistribution"
              - "cloudfront:CreateDistribution"
            Resource: "*"
      Roles:
        - !Ref ExecutionRole
