AWSTemplateFormatVersion: "2010-09-09"
Description: Visitor Prioritization Website
Parameters:
  BucketName:
    Description: Name of the S3 bucket
    Type: String
Resources:
  Website:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
Outputs:
  BucketDomainName:
    Value: !GetAtt
      - Website
      - DomainName
