AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  Generator: "former2"
Description: "Visitor Prioritization Website"
Parameters:
  BucketName:
    Description: Name of the S3 bucket
    Type: String
Resources:
  Website:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          -
            DomainName: !GetAtt
              - Website
              - DomainName
            Id: !Join [ "-", [ "S3", !Ref BucketName ] ]
            OriginPath: ""
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          AllowedMethods:
            - "HEAD"
            - "GET"
          CachedMethods:
            - "HEAD"
            - "GET"
          Compress: false
          DefaultTTL: 86400
          ForwardedValues:
              Cookies:
                  Forward: "none"
              QueryString: false
          MaxTTL: 31536000
          MinTTL: 0
          SmoothStreaming: false
          TargetOriginId: !Join [ "-", [ "S3", !Ref BucketName ] ]
          ViewerProtocolPolicy: "allow-all"
        CacheBehaviors:
          -
            AllowedMethods:
              - "HEAD"
              - "GET"
            CachedMethods:
              - "HEAD"
              - "GET"
            Compress: false
            DefaultTTL: 0
            ForwardedValues:
              Cookies:
                Forward: "all"
              QueryString: false
            MaxTTL: 0
            MinTTL: 0
            PathPattern: "/shop/*"
            SmoothStreaming: false
            TargetOriginId: !Join [ "-", [ "S3", !Ref BucketName ] ]
            ViewerProtocolPolicy: "allow-all"
        Comment: "Visitor prioritization demo"
        PriceClass: "PriceClass_100"
        Enabled: true
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
          MinimumProtocolVersion: "TLSv1"
        Restrictions:
          GeoRestriction:
            RestrictionType: "none"
        HttpVersion: "http2"
        IPV6Enabled: true
      Tags:
        -
          Key: "Demo"
          Value: "true"
        -
          Key: "Project"
          Value: "Visitor prioritization"
Outputs:
  CloudFrontDomain:
    Value: !GetAtt
      - CloudFrontDistribution
      - DomainName
